# Generated by Django 5.2.1 on 2026-09-26 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('system_temp', '系统临时文件'), ('pycache', 'Python 字节码缓存'), ('pip_cache', 'pip 下载缓存'), ('platform_data', '平台过期采集数据'), ('memory', '内存整理')], max_length=32, verbose_name='清理项')),
                ('ok', models.BooleanField(default=True, verbose_name='是否成功')),
                ('freed_bytes', models.BigIntegerField(default=0, verbose_name='释放空间(字节)')),
                ('files', models.IntegerField(default=0, verbose_name='处理文件数')),
                ('detail', models.TextField(blank=True, default='', verbose_name='明细')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='时间')),
            ],
            options={
                'verbose_name': '清理记录',
                'verbose_name_plural': '清理记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
