# Generated by Django 5.2.1 on 2026-09-25 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='local', max_length=128, verbose_name='主机名')),
                ('cpu_percent', models.FloatField(verbose_name='CPU 使用率(%)')),
                ('cpu_cores', models.IntegerField(default=0, verbose_name='逻辑核心数')),
                ('load_avg', models.FloatField(default=0.0, verbose_name='负载(1min)')),
                ('mem_percent', models.FloatField(verbose_name='内存使用率(%)')),
                ('mem_used_mb', models.FloatField(default=0.0, verbose_name='已用内存(MB)')),
                ('mem_total_mb', models.FloatField(default=0.0, verbose_name='总内存(MB)')),
                ('disk_percent', models.FloatField(default=0.0, verbose_name='系统盘使用率(%)')),
                ('disk_used_gb', models.FloatField(default=0.0, verbose_name='系统盘已用(GB)')),
                ('disk_total_gb', models.FloatField(default=0.0, verbose_name='系统盘总量(GB)')),
                ('net_sent_kbps', models.FloatField(default=0.0, verbose_name='上行速率(KB/s)')),
                ('net_recv_kbps', models.FloatField(default=0.0, verbose_name='下行速率(KB/s)')),
                ('proc_count', models.IntegerField(default=0, verbose_name='进程数')),
                ('tcp_conns', models.IntegerField(default=0, verbose_name='TCP 连接数')),
                ('simulated', models.BooleanField(default=False, verbose_name='是否模拟数据')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='采集时间')),
            ],
            options={
                'verbose_name': '主机指标',
                'verbose_name_plural': '主机指标',
                'ordering': ['-created_at'],
            },
        ),
    ]
