# Generated by Django 5.2.1 on 2026-09-25 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RumEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pv', '页面访问'), ('perf', '页面性能'), ('api', 'API调用'), ('error', 'JS错误'), ('resource', '静态资源'), ('custom', '自定义事件')], db_index=True, max_length=16, verbose_name='事件类型')),
                ('app', models.CharField(default='forum', max_length=32, verbose_name='应用标识')),
                ('page_url', models.CharField(blank=True, default='', max_length=256, verbose_name='页面URL')),
                ('referrer', models.CharField(blank=True, default='', max_length=256, verbose_name='来源页')),
                ('session_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='会话ID')),
                ('device', models.CharField(blank=True, default='', max_length=80, verbose_name='浏览器/系统')),
                ('screen', models.CharField(blank=True, default='', max_length=20, verbose_name='分辨率')),
                ('ttfb_ms', models.FloatField(blank=True, null=True, verbose_name='TTFB(ms)')),
                ('dom_ready_ms', models.FloatField(blank=True, null=True, verbose_name='DOMReady(ms)')),
                ('load_ms', models.FloatField(blank=True, null=True, verbose_name='完整加载(ms)')),
                ('fp_ms', models.FloatField(blank=True, null=True, verbose_name='首次绘制FP(ms)')),
                ('fcp_ms', models.FloatField(blank=True, null=True, verbose_name='首次内容绘制FCP(ms)')),
                ('lcp_ms', models.FloatField(blank=True, null=True, verbose_name='最大内容绘制LCP(ms)')),
                ('api_url', models.CharField(blank=True, default='', max_length=256, verbose_name='API地址')),
                ('api_method', models.CharField(blank=True, default='', max_length=10, verbose_name='请求方法')),
                ('api_status', models.IntegerField(blank=True, null=True, verbose_name='状态码')),
                ('api_duration_ms', models.FloatField(blank=True, null=True, verbose_name='API耗时(ms)')),
                ('api_ok', models.BooleanField(default=True, verbose_name='是否成功')),
                ('err_message', models.CharField(blank=True, default='', max_length=300, verbose_name='错误信息')),
                ('err_stack', models.TextField(blank=True, default='', verbose_name='错误堆栈')),
                ('r_type', models.CharField(blank=True, default='', max_length=16, verbose_name='资源类型')),
                ('r_url', models.CharField(blank=True, default='', max_length=256, verbose_name='资源地址')),
                ('r_duration_ms', models.FloatField(blank=True, null=True, verbose_name='加载耗时(ms)')),
                ('r_size_kb', models.FloatField(blank=True, null=True, verbose_name='传输大小(KB)')),
                ('event_name', models.CharField(blank=True, default='', max_length=64, verbose_name='事件名')),
                ('payload', models.TextField(blank=True, default='', verbose_name='负载(JSON)')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='上报时间')),
            ],
            options={
                'verbose_name': 'RUM事件',
                'verbose_name_plural': 'RUM事件',
                'ordering': ['-created_at'],
            },
        ),
    ]
