# Generated by Django 5.2.1 on 2026-09-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=200, verbose_name='请求路径')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='HTTP 方法')),
                ('status_code', models.IntegerField(default=200, verbose_name='状态码')),
                ('duration_ms', models.FloatField(verbose_name='总耗时(ms)')),
                ('sql_count', models.IntegerField(default=0, verbose_name='SQL 查询次数')),
                ('sql_time_ms', models.FloatField(default=0.0, verbose_name='SQL 累计耗时(ms)')),
                ('slow_queries', models.TextField(default='[]', verbose_name='慢查询明细(JSON)')),
                ('slow_query_count', models.IntegerField(default=0, verbose_name='慢查询条数')),
                ('cpu_percent', models.FloatField(default=0.0, verbose_name='CPU 占用(模拟)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='采集时间')),
            ],
            options={
                'verbose_name': '请求指标',
                'verbose_name_plural': '请求指标',
                'ordering': ['-created_at'],
            },
        ),
    ]
