# Generated by Django 5.2.1 on 2026-09-25 21:08

import django.utils.timezone
import monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='指标名')),
                ('labels', models.TextField(default='{}', verbose_name='标签(JSON)')),
                ('value', models.FloatField(verbose_name='数值')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='采集时间')),
            ],
            options={
                'verbose_name': '自定义指标',
                'verbose_name_plural': '自定义指标',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='卡片标题')),
                ('metric_key', models.CharField(max_length=64, verbose_name='指标Key')),
                ('chart_type', models.CharField(choices=[('line', '折线'), ('area', '面积'), ('bar', '柱状')], default='line', max_length=10, verbose_name='图表类型')),
                ('minutes', models.IntegerField(default=60, verbose_name='时间范围(分钟)')),
                ('span', models.IntegerField(default=1, verbose_name='栅格宽度(1-3)')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '大盘卡片',
                'verbose_name_plural': '大盘卡片',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='client_ip',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='客户端IP'),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='is_error',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否错误请求'),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='spans',
            field=models.TextField(default='[]', verbose_name='调用链Span(JSON)'),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='trace_id',
            field=models.CharField(db_index=True, default=monitor.models.gen_trace_id, max_length=32, verbose_name='TraceID'),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='view_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='视图名'),
        ),
        migrations.AlterField(
            model_name='requestmetric',
            name='cpu_percent',
            field=models.FloatField(default=0.0, verbose_name='CPU 占用(推算)'),
        ),
        migrations.AlterField(
            model_name='requestmetric',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='采集时间'),
        ),
    ]
