# Generated by Django 5.2.1 on 2026-09-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_custommetric_dashcard_requestmetric_client_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmetric',
            name='geo_city',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='归属城市'),
        ),
        migrations.AddField(
            model_name='requestmetric',
            name='geo_province',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, verbose_name='归属省份'),
        ),
        migrations.AlterField(
            model_name='requestmetric',
            name='client_ip',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='客户端IP'),
        ),
    ]
