# Generated by Django 5.2.1 on 2026-09-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_requestmetric_geo_city_requestmetric_geo_province_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='requestmetric',
            index=models.Index(fields=['duration_ms'], name='idx_req_duration'),
        ),
        migrations.AddIndex(
            model_name='requestmetric',
            index=models.Index(fields=['path', 'created_at'], name='idx_req_path_time'),
        ),
        migrations.AddIndex(
            model_name='requestmetric',
            index=models.Index(fields=['slow_query_count'], name='idx_req_slowq'),
        ),
        migrations.AddIndex(
            model_name='requestmetric',
            index=models.Index(fields=['geo_province', 'created_at'], name='idx_req_geo_time'),
        ),
    ]
