# Generated by Django 6.1.1 on 2026-09-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_requestmetric_idx_req_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='任务名')),
                ('holder', models.CharField(blank=True, default='', max_length=120, verbose_name='持有者')),
                ('term', models.BigIntegerField(default=0, verbose_name='任期')),
                ('acquired_at', models.DateTimeField(blank=True, null=True, verbose_name='本次持有起点')),
                ('renewed_at', models.DateTimeField(blank=True, null=True, verbose_name='最近续约')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='租约到期')),
            ],
            options={
                'verbose_name': '任务租约',
                'verbose_name_plural': '任务租约',
                'ordering': ['name'],
            },
        ),
    ]
