# Generated by Django 5.2.1 on 2026-09-26 06:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0002_alertevent_ack_at_alertevent_ack_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(db_index=True, max_length=128, verbose_name='主机名/标识')),
                ('label', models.CharField(blank=True, default='', max_length=80, verbose_name='名称')),
                ('kind', models.CharField(choices=[('主机', '主机'), ('应用', '应用'), ('数据库', '数据库'), ('中间件', '中间件'), ('其他', '其他')], default='主机', max_length=10, verbose_name='类型')),
                ('env', models.CharField(choices=[('生产', '生产'), ('测试', '测试'), ('开发', '开发'), ('未分类', '未分类')], default='未分类', max_length=10, verbose_name='环境')),
                ('owner', models.CharField(blank=True, default='', max_length=40, verbose_name='负责人')),
                ('notes', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('auto', models.BooleanField(default=True, verbose_name='自动登记')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='最近上线')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
                'ordering': ['env', 'hostname'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='', max_length=60, verbose_name='用户')),
                ('action', models.CharField(max_length=60, verbose_name='动作')),
                ('target', models.CharField(blank=True, default='', max_length=150, verbose_name='对象')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情')),
                ('ip', models.CharField(blank=True, default='', max_length=64, verbose_name='IP')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='时间')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('status', models.CharField(choices=[('open', '处理中'), ('resolved', '已恢复'), ('closed', '已关闭')], default='open', max_length=10, verbose_name='状态')),
                ('level', models.CharField(default='P2', max_length=4, verbose_name='最高级别')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='开始时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='恢复时间')),
                ('services', models.CharField(blank=True, default='', max_length=200, verbose_name='涉及服务')),
                ('root_cause', models.TextField(blank=True, default='', verbose_name='根因分析')),
                ('lessons', models.TextField(blank=True, default='', verbose_name='改进措施')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '故障事件',
                'verbose_name_plural': '故障事件',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(default='manual', max_length=10, verbose_name='触发方式')),
                ('score', models.IntegerField(default=100, verbose_name='健康评分')),
                ('results', models.TextField(default='[]', verbose_name='检查结果(JSON)')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='时间')),
            ],
            options={
                'verbose_name': '巡检报告',
                'verbose_name_plural': '巡检报告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotifyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用外部通知')),
                ('smtp_host', models.CharField(blank=True, default='', max_length=120, verbose_name='SMTP 服务器')),
                ('smtp_port', models.IntegerField(default=465, verbose_name='SMTP 端口')),
                ('smtp_ssl', models.BooleanField(default=True, verbose_name='SMTP 使用 SSL')),
                ('smtp_user', models.CharField(blank=True, default='', max_length=120, verbose_name='SMTP 用户')),
                ('smtp_pass', models.CharField(blank=True, default='', max_length=120, verbose_name='SMTP 密码/授权码')),
                ('mail_from', models.CharField(blank=True, default='', max_length=120, verbose_name='发件人')),
                ('mail_to', models.CharField(blank=True, default='', max_length=300, verbose_name='收件人(逗号分隔)')),
                ('webhook_generic', models.CharField(blank=True, default='', max_length=300, verbose_name='通用 Webhook URL')),
                ('wecom_webhook', models.CharField(blank=True, default='', max_length=300, verbose_name='企业微信 Webhook')),
                ('ding_webhook', models.CharField(blank=True, default='', max_length=300, verbose_name='钉钉 Webhook')),
            ],
            options={
                'verbose_name': '通知渠道配置',
                'verbose_name_plural': '通知渠道配置',
            },
        ),
        migrations.CreateModel(
            name='ProbeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='任务名')),
                ('url', models.CharField(max_length=300, verbose_name='拨测地址')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='方法')),
                ('expect_status', models.IntegerField(default=200, verbose_name='期望状态码')),
                ('keyword', models.CharField(blank=True, default='', max_length=100, verbose_name='页面须包含关键字(可选)')),
                ('timeout_sec', models.IntegerField(default=10, verbose_name='超时(秒)')),
                ('interval_sec', models.IntegerField(default=60, verbose_name='频率(秒)')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('last_ok', models.BooleanField(default=False, verbose_name='最近成功')),
                ('last_status', models.IntegerField(default=0, verbose_name='最近状态码')),
                ('last_ms', models.FloatField(default=0.0, verbose_name='最近耗时(ms)')),
                ('last_error', models.CharField(blank=True, default='', max_length=200, verbose_name='最近错误')),
                ('last_cert_days', models.IntegerField(blank=True, null=True, verbose_name='证书剩余天数')),
                ('consecutive_fails', models.IntegerField(default=0, verbose_name='连续失败次数')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='下次执行')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '拨测任务',
                'verbose_name_plural': '拨测任务',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='SLO 名称')),
                ('target_availability', models.FloatField(default=99.9, verbose_name='可用性目标(%)')),
                ('target_p95_ms', models.FloatField(default=500, verbose_name='P95 耗时目标(ms)')),
                ('window_days', models.IntegerField(default=30, verbose_name='统计窗口(天)')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'SLO',
                'verbose_name_plural': 'SLO',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HealAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='动作名称')),
                ('action_type', models.CharField(choices=[('cleanup_tmp', '清理临时目录'), ('http_callback', 'HTTP 回调'), ('command', '自定义命令(谨慎)')], default='cleanup_tmp', max_length=20, verbose_name='类型')),
                ('param', models.CharField(blank=True, default='', max_length=300, verbose_name='参数(目录/URL/命令)')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用')),
                ('cooldown_min', models.IntegerField(default=30, verbose_name='冷却(分钟)')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最近执行')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heal_actions', to='alerts.alertpolicy', verbose_name='触发策略')),
            ],
            options={
                'verbose_name': '自愈动作',
                'verbose_name_plural': '自愈动作',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HealRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=True, verbose_name='是否成功')),
                ('output', models.TextField(blank=True, default='', verbose_name='输出')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='时间')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ops.healaction', verbose_name='动作')),
            ],
            options={
                'verbose_name': '自愈执行记录',
                'verbose_name_plural': '自愈执行记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProbeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(verbose_name='是否成功')),
                ('status_code', models.IntegerField(default=0, verbose_name='状态码')),
                ('duration_ms', models.FloatField(default=0.0, verbose_name='耗时(ms)')),
                ('error', models.CharField(blank=True, default='', max_length=200, verbose_name='错误')),
                ('cert_days', models.IntegerField(blank=True, null=True, verbose_name='证书剩余天数')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ops.probetask', verbose_name='拨测任务')),
            ],
            options={
                'verbose_name': '拨测结果',
                'verbose_name_plural': '拨测结果',
                'ordering': ['-created_at'],
            },
        ),
    ]
