# Generated by Django 5.2.1 on 2026-09-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionrun',
            name='trigger',
            field=models.CharField(choices=[('manual', '手动'), ('scheduled', '定时')], default='manual', max_length=10, verbose_name='触发方式'),
        ),
    ]
