# Generated by Django 5.2.1 on 2026-09-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_alter_inspectionrun_trigger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='probetask',
            options={'ordering': ['next_run_at', 'id'], 'verbose_name': '拨测任务', 'verbose_name_plural': '拨测任务'},
        ),
        migrations.AddField(
            model_name='probetask',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='如接入令牌用 {"X-OBS-Token": "..."} 放在请求头，避免拼进 URL 泄露', verbose_name='请求头(JSON)'),
        ),
        migrations.AlterField(
            model_name='notifyconfig',
            name='smtp_pass',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='SMTP 密码/授权码(加密存储)'),
        ),
        migrations.AddIndex(
            model_name='proberesult',
            index=models.Index(fields=['task', '-created_at'], name='idx_probe_task_time'),
        ),
    ]
