# Generated by Django 5.2.1 on 2026-09-25 21:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='策略名称')),
                ('metric_key', models.CharField(db_index=True, max_length=64, verbose_name='监控指标')),
                ('operator', models.CharField(choices=[('>', '大于'), ('<', '小于')], default='>', max_length=2, verbose_name='比较符')),
                ('threshold', models.FloatField(verbose_name='阈值')),
                ('level', models.CharField(choices=[('P0', 'P0 紧急'), ('P1', 'P1 严重'), ('P2', 'P2 警告'), ('提示', '提示')], default='P2', max_length=4, verbose_name='告警级别')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '告警策略',
                'verbose_name_plural': '告警策略',
                'ordering': ['level', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('firing', '触发中'), ('resolved', '已恢复')], default='firing', max_length=10, verbose_name='状态')),
                ('level', models.CharField(default='P2', max_length=4, verbose_name='级别')),
                ('value', models.FloatField(default=0.0, verbose_name='触发时数值')),
                ('summary', models.CharField(blank=True, default='', max_length=250, verbose_name='摘要')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='触发时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='恢复时间')),
                ('last_value_at', models.DateTimeField(blank=True, null=True, verbose_name='最近评估')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.alertpolicy', verbose_name='所属策略')),
            ],
            options={
                'verbose_name': '告警事件',
                'verbose_name_plural': '告警事件',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('站内信', '站内信'), ('webhook', 'Webhook(模拟)'), ('邮件(模拟)', '邮件(模拟)')], default='站内信', max_length=16, verbose_name='渠道')),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alertevent', verbose_name='关联事件')),
            ],
            options={
                'verbose_name': '通知记录',
                'verbose_name_plural': '通知记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
