# Generated by Django 5.2.1 on 2026-09-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='ack_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认时间'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='ack_by',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='handle_note',
            field=models.TextField(blank=True, default='', verbose_name='处理备注'),
        ),
    ]
