# Generated by Django 5.2.1 on 2026-09-26 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alertevent_ack_at_alertevent_ack_by_and_more'),
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='ops.incident', verbose_name='所属故障单'),
        ),
        migrations.AddField(
            model_name='alertpolicy',
            name='silenced_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='静默至'),
        ),
    ]
