# Generated by Django 5.2.1 on 2026-09-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alertevent_incident_alertpolicy_silenced_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrecord',
            name='kind',
            field=models.CharField(choices=[('fire', '触发'), ('resolve', '恢复')], default='fire', max_length=10, verbose_name='类型'),
        ),
    ]
