# Generated by Django 5.2.1 on 2026-09-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_notificationrecord_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertpolicy',
            name='breach_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='首次越限时间'),
        ),
        migrations.AddField(
            model_name='alertpolicy',
            name='for_minutes',
            field=models.FloatField(default=0, verbose_name='持续N分钟才触发'),
        ),
        migrations.AddField(
            model_name='alertpolicy',
            name='resolve_threshold',
            field=models.FloatField(blank=True, null=True, verbose_name='恢复阈值'),
        ),
    ]
