# Generated by Django 5.2.1 on 2026-09-25 21:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('system', '系统'), ('app', '应用'), ('api', '接入API'), ('rum', '前端RUM')], db_index=True, default='app', max_length=16, verbose_name='来源')),
                ('level', models.CharField(db_index=True, default='INFO', max_length=10, verbose_name='级别')),
                ('logger', models.CharField(blank=True, default='', max_length=120, verbose_name='记录器')),
                ('message', models.TextField(verbose_name='内容')),
                ('extra', models.TextField(blank=True, default='', verbose_name='附加信息(JSON)')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='时间')),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
