# Generated by Django 5.2.1 on 2026-09-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loghub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='trace_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='TraceID'),
        ),
    ]
